apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: nl-task2-3
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Хелло тхере! Айм юзе ConfigMap</title>
    </head>
    <body>
      <h1>Привет от Kubernetes и Нетологии!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nl-task2-3
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
